package com.epam.command;

public enum CommandName {
    SIGN_IN,
    SIGN_UP,
    INDEX,
    WRONG_REQUEST,
    MEDICAMENT,
    MEDICAMENTS,
    ADD_MEDICAMENT,
    MEDICAMENTS_BY_PRODUCER,
    MEDICAMENTS_BY_NAME,
    MEDICAMENTS_ASC_SORTED_BY_PRICE,
    MEDICAMENTS_DESC_SORTED_BY_PRICE,
    NEW_MEDICAMENT,
    EDIT_MEDICAMENT,
    SIGN_OUT,
    GET_ALL_USERS,
    GET_ALL_PHARMACISTS,
    GET_ALL_DOCTORS,
    NEW_PRESCRIPTION,
    ADD_PRESCRIPTION,
    ADD_TO_BASKET, CHECKOUT, BASKET, ADD_USER, NEW_USER, GET_USERS, GET_MEDICAMENTS;
}
