package bsuir.vintsarevich.enumeration;

public enum CommandName {
    SIGN_IN, SIGN_UP, SIGN_OUT, INDEX, WRONG_REQUEST, BASKET, CHANGE_LOCALE, ADD_PRODUCT, ADD_PRODUCT_TO_BASKET, REMOVE_PRODUCT_FROM_BASKET,
    ADD_ACCOUNT, EDIT_CLIENTS, CHANGE_CLIENT_STATUS;
}
